### ISSUE TITLE
What is this error?

### ISSUE THREAD

**Issue by TheNonSmoker** [aivarasatk/MultiSourceTorrentDownloader#7]
Screenshot: (https://user-images.githubusercontent.com/30073064/133857086-5f8942dd-f69b-412a-b24a-466e5e182116.png)

**Comment by aivarasatk** [comment]
Hi, did this happen when the application was run the first time? Have you changed anything manually with the configuration files? Do you have admin access with current user?

**Comment by TheNonSmoker** [comment]
Yes this happened in the first run
No haven't changed or tweaked anything
Yes I'm the admin of my PC

Btw this error came visible for a sec, I was lucky enough to snip it.

**Comment by aivarasatk** [comment]
Sorry for late response, I assume you used the latest release?

**Comment by aivarasatk** [comment]
@[Soumyadeep98O](https://github.com/Soumyadeep98O) In local files %AppData%\Local\MultiSourceTorrentDownloader you will find three *.json files. Open them all and add curly braces like this - {} and save
![image](https://user-images.githubusercontent.com/42089270/153043034-c6a3ebbd-93fc-4236-b5bc-790c9bd10432.png)

**Comment by TheNonSmoker** [comment]
Ok, Thanks 👍
